# This is a basic workflow to help you get started with Actions

name: Build Vayu

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout branch
      - uses: actions/checkout@v4
        with:
          ref: 'vayu-r-oss'

      - name: Android kernel build
        uses: lemniskett/android-kernel-actions@master
        id: build
        env:
          NAME: Vayu-Kernel
        with:
          arch: arm64
          compiler: gcc/10
          defconfig: vince_defconfig
          image: Image.gz-dtb

      - name: Release build
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.build.outputs.outfile }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      

        
